# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy JAR app to Azure Web App - blood-pressure-calculator

env:
  URI: https://blood-pressure-calculator.azurewebsites.net/
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install --file ./CA1/
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Build Vaadin with Maven 
        run: mvn package -Pproduction --file ./CA1/
      
      - name: Configure App with Maven 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
             
      
      #- name: Deploy using Maven
        #run: mvn azure-webapp:deploy --file ./CA1/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/CA1/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blood-pressure-calculator'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_06A4C5DBBA3043C1A21D7E050CB29B88 }}
          package: '*.jar'
          
      - name: K6 load Test
        uses: actions/checkout@v2

      - name: Pull Docker image for k6
        run: docker pull loadimpact/k6

      - name: Run k6 load test, capture report
        run: docker run -i loadimpact/k6 run - <CA1/k6Test/config.js > k6report.txt

      - uses: actions/upload-artifact@v2
        with:
          name: k6report
          path: k6report.txt
          
# OWASP ZAP baseline scan in docker container
# run baseline scan on URI and store test result file via volume mounted on container

      - name: Pull Docker image for ZAP
        run: docker pull owasp/zap2docker-weekly

      - name: Run baseline scan
        run: docker run -v /report:/zap/wrk/:rw --user root -t owasp/zap2docker-weekly zap-baseline.py -t ${{env.URI}} -I -r zapreport.html
  
      - uses: actions/upload-artifact@v2
        name: upload ZAP report
        with:
          name: ZAPreport
          path: /report/zapreport.html
